version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets:
      - db_password
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - backend

  app:
    image: flask-image-sw   
    depends_on:
      - db
    ports:
      - "5000:5000"
    deploy:
      update_config:
        parallelism: 1
        delay: 5s
    networks:
      - backend

volumes:
  db_data:

secrets:
  db_password:
    file: ./secrets/db_password.txt

networks:
  backend:
