version: '3.9'

services:
  flask:
    build: ./app
    container_name: flask_app2
    ports:
      - "${APP_PORT}:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV}
    networks:
      - mynet

  nginx:
    image: nginx:alpine
    container_name: nginx_web3
    ports:
      - "9000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
    networks:
      - mynet

networks:
  mynet:
